spring:
  application:
    name: DubboProviderBootstrap

dubbo:
  # 扫描
  scan:
    base-packages: com.dubbo.provider.service
  protocol:
    name: dubbo

    # 端口随机，否则在一个机器上启动两个dubbo服务会端口冲突
    port: -1

  registry:
    address: nacos://127.0.0.1:8848
    password: nacos
    username: nacos
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache

  # Consumer端必须要去注册中心才能拿到 token
  provider:
    token: password123456
  application:
    logger: log4j2
demo:
  service:
    version: 2.0.0


logging:
  level:
    org.springframework.web: DEBUG
