spring:
  application:
    name: sharding-sphere
  sharding-sphere:
    datasource:
      names: db1
      db1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/java?characterEncoding=utf-8
        username: root
        password: test-2021
    rules:
      sharding:
        tables:
          city:
            actual-data-nodes: db1.city_$->{0..1}
            key-generate-strategy:
              key-generator-name: snowflake
              column: id
            table-strategy:
              standard:
                sharding-column: id
                sharding-algorithm-name: t-city-inline
        sharding-algorithms:
          t-city-inline:
            type: INLINE
            props:
              algorithm-expression: city_$->{id % 2}
        key-generators:
          snowflake:
            type: SNOWFLAKE
    props:
      sql-show: true
    mode:
      # 设置单机模式
      type: Standalone
      overwrite: true

