server:
  port: 8080
spring:
  redis:
    port: 6379
    database: 2
    sentinel:
      master: redis-master
      nodes:
        - 172.28.48.1:26379
        - 172.28.48.1:26380
        - 172.28.48.1:26381
    lettuce:
      pool:
        max-active: 8
    password: dj-uk2022
