server:
  port: 8080
spring:
  redis:
    port: 6379
    database: 2
    sentinel:
      master: redis-master
      nodes:
        - 172.24.0.1:26379
        - 172.24.0.1:26380
        - 172.24.0.1:26381
