spring:
  datasource:
    username: root
    password: test-2021
    url: jdbc:mysql://localhost:3306/java?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
#    默认是0
    database: 8
    port: 6379
    host: localhost

mybatis:
#  mybatis配置，配置缓存开启等
  config-location: classpath:mybatis/mybatis-config.xml
#  数据库查询语句的路径
  mapper-locations: classpath:mybatis/mapper/*.xml
# 类的别名，有了这个就不用在*Mapper.xml文件里的resultMap的type标签里写包名了
  type-aliases-package: com.mybatis.model

logging:
  level:
    com.mybatis: DEBUG
#    org.springframework.boot: DEBUG