spring:
  datasource:
#    username: root
#    password: test-2021
#    url: jdbc:mysql://localhost:3306/java?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:oracle:thin:@192.168.191.53:1521/djwk
    username: cs20210912
    password: cs20210912
    driver-class-name: oracle.jdbc.OracleDriver


logging:
  level:
    com.mybatis: DEBUG
#    org.springframework.boot: DEBUG