server:
  port: 8080

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO

jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 使用Base64对该令牌进行编码
  base64-secret: mzTNypPIctGSAkzb2iuZDIMDdVnhYl3bAqx+qe6gdfss4CcG/qpfz8hKfpfF2Ir/RHNYCsDzwE1/h7N7D4Z/bA==
  # 令牌过期时间 （小时）
  token-validity-in-minutes: 12
