spring:
  datasource:
    dynamic:
      primary: mysql #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        mysql:
          username: root
          password: test-2021
          url: jdbc:mysql://localhost:3307/java?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
          driver-class-name: com.mysql.cj.jdbc.Driver
        h2:
          driver-class-name: org.h2.Driver
          url: jdbc:h2:mem:test
          username: root
          password: test
          schema: classpath:db/schema-h2.sql
          data: classpath:db/data-h2.sql
#        erp:
#          url: jdbc:oracle:thin:@192.168.191.53:1521/djwk
#          username: cs20210912
#          password: cs20210912
#          driver-class-name: oracle.jdbc.OracleDriver

logging:
  level:
    com.mybatis: DEBUG
    com.baomidou: debug
    org.springframework.boot: INFO