server:
  port: 8080
logging:
  level:
    com.chiang.logback: info

mybatis-plus:
  check-config-location: true
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler

spring:
  datasource:
    druid:
      stat-view-servlet:
        enabled: false
      web-stat-filter:
        enabled: false
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/ddd?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: test-2021